# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                  : Computational Chemistry from  Laptop to HPC
author                 : The eChem team
copyright              : "2023"
logo                   : img/logo.png
exclude_patterns       : [ README.md, standards.md, docs/elec_struct/wft_sol.ipynb, docs/mol_struct/md_biased.ipynb, docs/tutorials/dich.ipynb, docs/tutorials/mag.ipynb, docs/tutorials/nlo.ipynb, docs/tutorials/photo.ipynb, docs/tutorials/react.ipynb, docs/tutorials/tm.ipynb, docs/tutorials/uv_vis_aspects.ipynb, docs/tutorials/uv_vis_large.ipynb, docs/spec_prop/tddft_tda.ipynb, docs/spec_prop/tddft_challenge.ipynb]
only_build_toc_files   : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 120

#Sphinx settings
#Force a more recent version of the math engine mathjax
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - docs/references.bib

# Information about where the book exists on the web
repository:
  url:  https://github.com/kthpanor/echem
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: img/favicon.png
  home_page_in_navbar: false
  google_analytics_id: G-TX4YJ1J5XE # for google analytics
